services:
  - type: web
    name: shopping-cart-api
    runtime: docker
    rootDir: shopping-cart-backend
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health/liveness
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_API_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: APP_FRONTEND_BASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ADMIN_SEED_USERNAME
        sync: false
      - key: ADMIN_SEED_PASSWORD
        sync: false
